### ISSUE TITLE
The bot cannot ping

### ISSUE THREAD

**Issue by bscongluanbui** [recitativonika/nodepay-network-bot#4]
An error occurred in call_api: 403 Client Error: Forbidden for url: https://nw.nodepay.org/api/network/ping
An error occurred in send_ping: 'NoneType' object is not subscriptable
Can you update this

**Comment by recitativonika** [comment]
I will check it later

**Comment by recitativonika** [comment]
I check it and it still working, it might be your IP/connection is blocked by Cloudflare
