### ISSUE TITLE
 An error occurred in call_api: 403 Client Error: Forbidden for url: https://nw.nodepay.org/api/network/ping

### ISSUE THREAD

**Issue by Choki625** [recitativonika/nodepay-network-bot#5]
An error occurred in call_api: 403 Client Error: Forbidden for url: https://nw.nodepay.org/api/network/ping

**Comment by recitativonika** [comment]
it seems the api for nodepay changed, I will check it later

**Comment by recitativonika** [comment]
pull the repo again
